### ISSUE TITLE
Make it harder to leave an organisation

### ISSUE THREAD

**Issue by Te-k** [pytition/Pytition#103]
**Is your feature request related to a problem? Please describe.**

Today it is really easy to leave an organisation as there is a button without warning in the dashboard, so it is really likely that at some point someone will click by mistake.

**Describe the solution you'd like**

Either add a warning, or move this feature in another less used webpage.

**Comment by Te-k** [comment]
Confirmed today, best solution is to have this option in the user's settings page. Several cases need to be handled like when the user is the last one from the organisation. I take this

**Comment by fallen** [comment]
ack!

**Comment by Te-k** [comment]
Done with #116
