### ISSUE TITLE
Possibility to migrate a petition to a new user or an organisation

### ISSUE THREAD

**Issue by Te-k** [pytition/Pytition#112]
**Is your feature request related to a problem? Please describe.**

Today it is not possible to migrate a petition to an organization or a new user. The common scenario would be someone creating a petition with their user and then deciding to create an organisation for it and migrate the petition.

**Describe the solution you'd like**

Have a button to migrate the petition to another user or org in the petition settings (github like)

I would keep that feature for at least v3, not a priority

**Comment by fallen** [comment]
Yes good idea!
