### ISSUE TITLE
New Feature: Allow image upload

### ISSUE THREAD

**Issue by Te-k** [pytition/Pytition#126]
**Is your feature request related to a problem? Please describe.**

Today it is not possible to easily upload an image. 

**Describe the solution you'd like**

Have a feature to upload images.

**Comment by fallen** [comment]
Implemented in https://github.com/pytition/Pytition/commit/789f7cb13b20adafc20be3ae59dda49c6bab9590
But we still need to provide an easy way to upload a "Twitter image" in the social network tab.
(for the record, this image is used to generate the opengraph tag with the picture)
