### ISSUE TITLE
No refresh on petition deletion

### ISSUE THREAD

**Issue by antoine-de** [pytition/Pytition#129]
**Describe the bug**
Deleting a petition on the user dashbord can lead to 500 errors.

**To Reproduce**
1. Go to the user's dashboard (should be the same for an organisation)
2. delete a petition
3. since the page is not reloaded, the petition is still there, so you can click on any of this petition's button (eg. edit)

by doing so, a 500 is raised.

**Expected behavior**
The petition should disappear just after it's deletion.

**Comment by fallen** [comment]
I guess the ajax query "done" handler should just refresh the page upon success.

**Comment by fallen** [comment]
Cannot reproduce.
Seems to have been fixed somehow.
However there was an issue in petition deletion for org's petitions.
Thanks!
