### ISSUE TITLE
Improve the footer

### ISSUE THREAD

**Issue by Te-k** [pytition/Pytition#136]
**Is your feature request related to a problem? Please describe.**

There is a footer on some pages and not on some others. I am not sure that the footer is helpful.

**Describe the solution you'd like**

Do we need a footer ? If yes to show what ? (not sure the github logo is really helpful there) How to show it ? (Sticky footer ?)

**Comment by numahell** [comment]
Usually, legal notices, privacy and CGU are linked in the footer. I agree that big github logo is not really helpful for people who want to sign or create petitions. 

Next question is, if we add legal notices and CGU (which are required), how could they be updated by admin of the pytition instance ?

**Comment by fallen** [comment]
I would allow admin to set the content of those pages via an HTML file path that can be set in settings.
Maybe we can provide default (with blanks to fill? or generic ?) ones also.

**Comment by numahell** [comment]
You would use a static HTML page, or a django HTML template to keep header and footer ?

**Comment by fallen** [comment]
Hmmm I would use a Django template that would inherit from the base one, to have the less possible boilerplate code in it. Just the "real content".
Provide a default one.
Let users provide their own in a variable in settings.

Or any other idea?

**Comment by fallen** [comment]
What has been done:

No footer at all by default.
If administrator wants a footer with GDPR / TOS / legal notice links, (s)he can set "TEMPLATE_FOOTER" variable in settings to a template path containing the footer template.

For the petition page, footer is configurable by the petition owner.
