### ISSUE TITLE
Update Model to reduce complexity

### ISSUE THREAD

**Issue by Te-k** [pytition/Pytition#143]
**Is your feature request related to a problem? Please describe.**

There are a few things in the model that make it more complex that it could be.

**Describe the solution you'd like**

Things to do : 
* Petition has a foreignKey user and a foreignKey organisation, and on create a function that raise an error if none of them or both of them is set
* Same for a template, two foreign keys and constraints on create to have only one set
* A permission has a foreign key for user (instead of the manytomany relationship today)

It should not have that much impact on the view, but the migration with previous versions may be hard to do, so I suggest having this done in V2.

**Comment by fallen** [comment]
Right, this is "big change".
I suggest that after the change is done, we just squash all v2.0 migration files into 1 migration.
Nobody should be using master branch in production, and I know no-one using it.
Only person I know using v1.0 is RAP today.

So it should be OK for RAP to migrate from v1.0 to v2.0 (when it is released) with the squashed migration file.

**Comment by fallen** [comment]
This is fixed by https://github.com/pytition/Pytition/pull/146
