### ISSUE TITLE
There is no way for users to get/see their org's or own profile page URL

### ISSUE THREAD

**Issue by fallen** [pytition/Pytition#144]
There is -as of today- no link to profile pages.

We need to find a way to give a "public profile link" to users and organizations and put it somewhere accessible.

But we also need to take care that most connected users usually want to go to their dashboards and not to their profiles.

What would be the solution for this?

**Comment by fallen** [comment]
For the user's profile page : maybe an entry in the top-right-corner dropdown menu?

But for the organizations' profile pages ... I don't see where to put the "profile link" info.

**Comment by thimy** [comment]
That could be in the side nav in the dashboard: "View own public page"

**Comment by fallen** [comment]
You mean putting a link to the "organization public profile page" on the left-side menu of the org dashboard?
