### ISSUE TITLE
Big blank + scrolling on register account page

### ISSUE THREAD

**Issue by fallen** [pytition/Pytition#145]
Problem: in register account page, form far away down the page, there is a big blank and the page scrolls
I am guessing this comes form the "app" class which is used without footer.

**Comment by fallen** [comment]
What do you think we can do @thimy ?

**Comment by numahell** [comment]
Is this bug fixed ? I see others problems in mobile mode, but not blank down the register page.

**Comment by numahell** [comment]
Ok it is not fixed, my screen was too small :]

**Comment by fallen** [comment]
Closed by https://github.com/pytition/Pytition/pull/149
