### ISSUE TITLE
Clarify the "Back to dashboard" button usage

### ISSUE THREAD

**Issue by fallen** [pytition/Pytition#164]
Clarify what it does and what it does not.
For instance, when already on user or org dashboard, the button is present, but does nothing. Maybe remove it?

Then only show it on pages which need to allow "going back to dashboard".
Maybe also spell exactly which dashboard it goes to? (user or org dashboard)

This needs clarification anyway, see email from Thomas about it.

**Comment by numahell** [comment]
It could be replaced by a breadcrumb or something like that ?
