### ISSUE TITLE
The "Sign" button is patially hidden when the petition text is too short vs the side text

### ISSUE THREAD

**Issue by Beexx** [pytition/Pytition#173]
**Describe the bug**
When the petition text is short (a few lines at most), and there is some text on the "side text" above the form, then the "SIGN" button is partially hidden below the footer. This is not scrollable.

**To Reproduce**
1. Create a petition
2. Write a small text on the first part (petition text that appears on the left): just one line.
3. Write a small text on the "side text" (text that appears above the form and the Sign button). One line is enough, the more you add the more you see the bug...
4. Display a preview of the petition. The side text is longer than the petition text, and the "sign" button disappears below the frame. No scroll bar is displayed.

**Expected behavior**
Adjust the height of both frames (left and right) to the maximum height of both frames. Or show a scroll bar (less practical).

**Screenshots**
![bug](https://user-images.githubusercontent.com/50069390/68131512-7bf06f80-ff1d-11e9-9d9a-bddd76104b69.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Firefox
 - Version 70.0.1 (64 bits)

**Comment by fallen** [comment]
See for instance: https://pytitiondemo.sionneau.net/petition/user/bristow/supprimons-les-panneaux-publicitaires-a-lyon-trop-cest-trop
Could you have a look at this if you have some time @numahell ? :)

**Comment by numahell** [comment]
Yes, I can have a look this weekend maybe.

**Comment by numahell** [comment]
Maybe this can help (I'll test this in the weekend)

```
.petition-wrapper {
    min-height: 580px;
}
```

**Comment by fallen** [comment]
By using the dev tools on Firefox, it seems your proposed change would fixe the issue :)

**Comment by fallen** [comment]
@numahell if you think this fix is good enough, can you send a PR? :)

**Comment by numahell** [comment]
I've tested it, and I think it will work for the example you gave, but not in every situation. I would like to use flex CSS to improve this part, I send a PR soon.

**Comment by fallen** [comment]
Thanks so much! You're saving me :)
