### ISSUE TITLE
Where do we setup SMTP credential for confirmation emails 

### ISSUE THREAD

**Issue by raphaeljolivet** [pytition/Pytition#181]
I don't see any option for the configuration of SMTP credentials for sending the confirmation emails.
I see some fields in the "migrations" (confirmation_email_smtp_host) but nothing available in the web interface nor the Djando admin.

Thanks for this app !

**Comment by fallen** [comment]
It used to be configurable per-petition, thus the fields you can see in the migration files.
Now it is a global setting, per Pytition instance.

It is the Django setting for all outgoing emails from the app, see: 
* https://docs.djangoproject.com/en/2.2/topics/email/#smtp-backend
* and all settings beginning at https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-EMAIL_HOST

**Comment by raphaeljolivet** [comment]
Thanks !
It works fine.

It might be good to import those settings from *env* and add inscruptions about it in INSTALL.md : Setting SMTP is a basic requirement for the app to work properly.

**Comment by fallen** [comment]
Definitely!
As you may have seen, there is no user documentation at all.
And the Install documentation is outdated: it's the one from v1.0.

So no usable documentation at all. This needs to be addressed, but no time :/

**Comment by fallen** [comment]
Out of curiosity @raphaeljolivet are you deploying an instance for yourself? for an organization?

**Comment by raphaeljolivet** [comment]
I have deployed it on a server of mine to host a singke petition of boycott of a mall I am fighting against. I did not want it to start from zero because we already had signatures from a previous campaign : 
https://petitions.atelier-des-communs.fr/petition/org/mysophiaantipolis/pre-boycott-de-opensky-a-sophia

**Comment by fallen** [comment]
Hey @raphaeljolivet you can now add "paper signatures" to your online petition so that you don't start from 0 if you already have signatures for this same cause.
This is in the petition edit page.
I am adding your instance to the instance list in the wiki: https://github.com/pytition/Pytition/wiki
