### ISSUE TITLE
Add possibility to (un)publish a petition from the configuration page

### ISSUE THREAD

**Issue by fallen** [pytition/Pytition#196]

**Comment by fallen** [comment]
This is done now, thanks to @lpoujade

**Comment by patterroni** [comment]
Adding the ability to (un)publish a petition from the configuration is a valuable feature. This would provide administrators with greater flexibility and control over petition visibility, allowing them to manage petitions more effectively based on their readiness or relevance. It would also streamline workflows by eliminating the need for separate tools or manual processes to change publication status.
