### ISSUE TITLE
List pytition instances

### ISSUE THREAD

**Issue by JLuc** [pytition/Pytition#216]
Is there a list of instances ?
In case there is none, could we start such a list ?

Instances could be classified as Public or Not-so-Public. 
Other categories or tags ?

This list could start on this report (or on a wikipage but the wiki looks closed).

**Comment by fallen** [comment]
No instance list so far, good idea to start one using the wiki!
We could classify those as Open to registration or not, I would think this would be more precise than public/not public but it's the same idea.
So far I know only those instances : 

* https://petition.antipub.org (not open to registration, reserved for R.A.P. members)
* https://pytitiondemo.sionneau.net , open for registration, only for demo. Do not host anything serious there.

And I think someone said in a ticket here that they have a private instance.

Would be great to see if there are other instances out there :)

**Comment by fallen** [comment]
There it is!
https://github.com/pytition/Pytition/wiki

Closing this one :)
