### ISSUE TITLE
Flag ALLOW_REGISTER not really active

### ISSUE THREAD

**Issue by bbmt-bbmt** [pytition/Pytition#225]
**Describe the bug**
Even if the flag ALLOW_REGISTER is set to False, if i add "/register" to the url, i can create a user

**To Reproduce**
1. Go to 'https://mydomain.org/petition/register/'
2. create a user and connect to this user to create new petition

**Expected behavior**
The url "https://mydomain.org/petition/register/" would show an error message if ALLOW_REGISTER is set to false

**Desktop (please complete the following information):**
 - OS: debian 10
 - firefox 75

**Comment by fallen** [comment]
You're absolutely right! Thanks for the report :)
Will fix ASAP!
