### ISSUE TITLE
Faire descendre le texte et le compteur aussi

### ISSUE THREAD

**Issue by ghost** [pytition/Pytition#23]
Quand on scroll vers le bas de page, le texte (ici "Signez la pétition !") et le compteur du nombre de signature ne descend pas avec le reste de la zone de droite mais disparaît.
Ça ne serait pas mieux de le garder en fixe aussi et de le faire descendre avec le reste ?

En haut de page :
![capture du 2018-02-08 16-56-12](https://user-images.githubusercontent.com/7694864/35983028-7bcd03e4-0cf1-11e8-9e1a-f07b0aecbbd0.png)

Et en descendant :
![capture du 2018-02-08 16-56-16](https://user-images.githubusercontent.com/7694864/35983029-7bf9512e-0cf1-11e8-9236-40c94ed96717.png)

**Comment by fallen** [comment]
Hmmm honnêtement j'ai l'impression que c'est mieux comme ça... demandons peut-être l'avis de Khaled ou Thomas ?

**Comment by Dostoi** [comment]
J'ai suis pas sûr non plus. Je me demandais justement

**Comment by fallen** [comment]
A priori c'est pas mal comme ça, je propose de laisser comme c'est :)
