### ISSUE TITLE
Remove signature form after signed or confirmed

### ISSUE THREAD

**Issue by martinlehoux** [pytition/Pytition#232]
**Is your feature request related to a problem? Please describe.**
I think that displaying the whole form for someone who is signing a petition is not very good ux.
<img src="https://user-images.githubusercontent.com/26896369/81630101-98340400-93b9-11ea-8829-c1550640a049.png" width="100px" />

**Describe the solution you'd like**
I simply want to remove the form and let the whole space for the message.

**Comment by martinlehoux** [comment]
What is the purpose of the progress bar above the message ? Should the message disappear after a certain time ?

**Comment by fallen** [comment]
Someone already gave me this feedback : the form needs to disappear upon successful signing. No point in showing it again.
We should only show the green "success" message, I fully agree.

The bar is meant to always be there, it's the "progress bar" showing the % of signatures over the signature target (which is configurable).
Like the progress bar in crowd-funding pages.

The green message will disappear as soon as you leave or refresh the page, it's only temporary and it is showed once.
I don't want to keep the information that someone signed the petition.
