### ISSUE TITLE
Add pagination for petitions

### ISSUE THREAD

**Issue by simpnu** [pytition/Pytition#240]
Hello there!

**Is your feature request related to a problem? Please describe.**
I find that the user experience lacks of fluidity when I want to access all the petitions. I first see only the top 12 then I need to access the page with all petitions which will start with the same 12 petitions.

It is also not very clear when there is fewer than 12 petitions, as the button "show all petitions" still appear and is basically pointless 

**Describe the solution you'd like**
I think it would be more fluid to add pagination directly on the home page, with 12 petitions per page to keep the same interface as currently.

**Additional context**
It's really easy to do so in Django, I can take care of this change, I just wanted to confirm first that this is something you want to be done :)

**Comment by fallen** [comment]
Very good idea!
Either pagination with links or auto "load more" on scroll down?

**Comment by simpnu** [comment]
I'd go with pagination at first - if that's ok for you - as it is natively supported in Django and will be fairly easy to add.

Then if someone wants to use auto-load instead because it is a better experience, it still can be done later on.
