### ISSUE TITLE
add upgrade section on documentation

### ISSUE THREAD

**Issue by bbmt-bbmt** [pytition/Pytition#244]
**Is your feature request related to a problem? Please describe.**
The actual documentation doesn't have an "how to upgrade section"
Some people may only do 'git pull' and 'git checkout version' and 'forget pip install upgrade'

**Describe the solution you'd like**
this command can be added to the documentation:

```bash
  $ git pull
  $ version=$(curl -s https://api.github.com/repos/pytition/pytition/releases/latest | grep "tag_name" | cut -d : -f2,3 | tr -d \" | tr -d ,)
  $ git checkout $version
  $ source pytition_venv/bin/activate
  (pytition_venv) $ pip3 install upgrade -r requirements.txt
```

**Comment by fallen** [comment]
Also tell to:
- [ ] backup database and media first somewhere, see #218 
- [ ] re-run : collectstatic, migrate, compilemessages
