### ISSUE TITLE
How do I change the name of the site/project?

### ISSUE THREAD

**Issue by mukberty** [pytition/Pytition#248]
How can I customise the name of the project, and the landing page. Is this possible?

**Comment by fallen** [comment]
You can set the `SITE_NAME` setting for instance: https://github.com/pytition/Pytition/blob/master/pytition/pytition/settings/base.py#L204
Modify this in your setting file, do not modify the source code in base.py

For the landing page you can setup those settings:
* INDEX_PAGE = 'HOME' : list of lastly published petitions, with their organization names
* INDEX_PAGE = 'ORGA_PROFILE' : list of lastly published petitions of the organization you specify in INDEX_PAGE_ORGA setting.
* INDEX_PAGE = 'USER_PROFILE' : same as previous but for a user, not an organization. You specify the user in INDEX_PAGE_USER.
* INDEX_PAGE = 'LOGIN_REGISTER' : it will redirect user to their dashboard if they are identified, if not it redirects to the "login" page.
