### ISSUE TITLE
Can users add a photo to appear in the image box of their petition instead of the pencil and pad?

### ISSUE THREAD

**Issue by mukberty** [pytition/Pytition#249]
I wished to know if users can add a photo to appear in the image box of their petition instead of the pencil and pad? If yes, how?
I felt doing so would make the site more attractive and petitions stand out.
Thanks.

**Comment by fallen** [comment]
You can upload a picture by going in the edit page of your petition, then go to "Social Network" tab, the "Twitter image" will be used on social networks when posting the petition link, it will also be used as a replacement for the pencil/pad picture on the petition site :)
I know this is not very well designed, the whole edit/creation page will need to be entirely rewritten to show a better and understandable design to better explain what is the purpose of each field.

**Comment by fallen** [comment]
An example of a Pytition instance using such pictures: https://petition.antipub.org

**Comment by mukberty** [comment]
Thanks a lot. 
i) What part of the code deals with this?
ii) What about changing the objective/aim (500 by default)?

Thanks a again :)

**Comment by fallen** [comment]
i) You mean, the code that deals with the picture upload? Or the code that deals with exposing the HTML OpenGraph tags?
ii) Changing the objective is possible, in the petition edit page, first tab. Or maybe that was not your question?

**Comment by mukberty** [comment]
i) Yes, the code that deals with the picture uploads.
ii) Thanks. Again, not so intuitive.
:)

**Comment by fallen** [comment]
HTML+js code is there: https://github.com/pytition/Pytition/blob/master/pytition/petition/templates/petition/edit_petition.html#L46
Python part is in the handling of the form: https://github.com/pytition/Pytition/blob/master/pytition/petition/views.py#L1215

**Comment by fallen** [comment]
Do you have more questions or do we close this ticket? :)
