### ISSUE TITLE
Have Pytition send an email upon account registration

### ISSUE THREAD

**Issue by fallen** [pytition/Pytition#252]
Several people were disturbed by the fact that they received 0 email when they created their account, even though it was successful.
They didn't have the idea to just login.

So let's make pytition send an email with something simple like "congratulations !! You successfully created your account !! Your login is `something`"

**Comment by fallen** [comment]
@lpoujade Could you also add the new configuration option to the documentation please?
It's just a matter of adding `.. autodata:: pytition.settings.base.ALLOW_REGISTER` to `doc/configuration.rst`
And then to add documentation style comment on top of `DEFAULT_NOREPLY_MAIL`
using the following syntax:

```python
#:| This is the documentation for DEFAULT_NOREPLY_MAIL
#:| It can be multi-line
DEFAULT_NOREPLY_MAIL = "noreply@domain.tld"
```

**Comment by lpoujade** [comment]
yes i'll do that !
