### ISSUE TITLE
Show petition creation date on petition page

### ISSUE THREAD

**Issue by fallen** [pytition/Pytition#294]
- [x] Make this optional
- [x] Allow to show either creation OR publication date

**Comment by rsk2** [comment]
Hi @fallen. I am interested in working on this issue, but first I wanted some help to understand it better. Can you please answer the following questions:

- When you say petition page, do you mean the user dashboard?
- How to make this optional? I am thinking the user needs to enable/disable it. Is that correct?

**Comment by fallen** [comment]
Hello @rsk2  thanks for your help on this :) It's much appreciated!

- I mean on the page where people can sign the petition, for instance this page https://demo.pytition.org/petition/user/55d00/pour-des-stands-de-materiels-doccasion-dans-nos-magasins-darts
- Yes the petition edition page can have some extra settings to enable showing the date on the petition page. This could be implemented by adding a new boolean field in the Petition model.

I would also:
- add two new date fields in the Petition model, to hold creation and publication date.
- prevent showing those if they are "0" (or NUL etc) for instance for petition created before this feature.
- allow the owner of the petition to edit those dates, to set them manually in case they are empty (if the petition was created before this feature existed) or if for instance they published/unpublished the petition several times and want to reset the date to some precise date.

Tell me what you think, and whether this is clear or not :)

**Comment by rsk2** [comment]
Ok, thanks @fallen. Since this issue involves a lot of changes, is it fine if I break it into multiple pull requests with incremental changes? That will make the pull requests easier for you to review as well.

**Comment by fallen** [comment]
Yes good idea! :+1:

**Comment by rsk2** [comment]
>     * allow the owner of the petition to edit those dates, to set them manually in case they are empty (if the petition was created before this feature existed) or if for instance they published/unpublished the petition several times and want to reset the date to some precise date.

Hi @fallen, on which page should I add the publication date so that it can be edited?

**Comment by fallen** [comment]
@rsk2 I would say on the petition edit page?
The one where you edit all the petition texts and settings. The `/petition/<int>/edit` one.

**Comment by rsk2** [comment]
@fallen, I have updated the PR

**Comment by rsk2** [comment]
@fallen, please review the PR

**Comment by fallen** [comment]
Wow sorry I completely forgot about this PR, I'll try to do the review ASAP!

**Comment by rsk2** [comment]
No problem @fallen

**Comment by rsk2** [comment]
Hi @fallen, can we close this issue?

**Comment by fallen** [comment]
Yes @rsk2 it's all good, thanks a lot :)

**Comment by rsk2** [comment]
Thank you @fallen :)
