### ISSUE TITLE
Class-based views

### ISSUE THREAD

**Issue by jherve** [pytition/Pytition#3]
https://github.com/fallen/Pytition/blob/6ac19522df7faab4c9e8b45ef8bca4df3ea4c44e/pytition/petition/views.py#L23

Vu que la validation des données ne parait pas spécialement triviale en survolant le code, et aussi parce que ça semble la manière standard de faire ça depuis pas mal de versions de Django, je te conseillerai de basculer sur les class-based views, qui ont toutes les méthodes qu'il faut pour gérer toutes les étapes entre la requete initiale et la sauvegarde du modèle 

https://docs.djangoproject.com/fr/1.11/topics/class-based-views/

T'as du coup juste besoin de surcharger qqes petites fonctions qui sont bien plus lisibles et debuggables ..

**Comment by fallen** [comment]
Ca te semble mieux comme ça : https://github.com/fallen/Pytition/commit/8a016b2b66e2635c3971a8205578cbe6e3d2c256 ?

**Comment by jherve** [comment]
C'est un pas dans la bonne direction mais à mon avis tu gagnerais bcp à bien refaire le découpage entre modèle (et ses méthodes clean et save) / formulaire (que tu ferais en Django plutot qu'à la paluche, et en utilisant sa méthode ... save, il me semble) / view (qui serait une CreateView puisque ce que tu fais c'est bien créer un nouvel objet :p et là t'aurais quasiment plus rien à faire, à part surcharger la méthode get_success_url)

Cf ici par exemple : https://docs.djangoproject.com/fr/1.11/topics/class-based-views/generic-editing/

Bon, je dis ça un peu comme si c'était évident mais faut pas m'en vouloir, au bout d'un moment tu deviens familier avec la philosophie du truc mais clairement ça prend du temps ... C'est puissant et ça permet d'économiser bcp de code inutile, mais c'est pas forcément méga intuitif (même si la doc' est super bien foutue)

**Comment by fallen** [comment]
Je garde l'idée en tête, bien souvent ça nécessite de faire plier ses idées au chausse pied pour que ça rentre dans les Class Based Views...
Mais je vais tenter de les utiliser quand c'est possible.
Thanks!
