### ISSUE TITLE
Add a share button in a petition's page 

### ISSUE THREAD

**Issue by agentspecial008** [pytition/Pytition#304]
We want to add on any petition's webpage a sharing wiidget, which allow an user to post the petition on a social media or to copy the petition's path on his clipboard by clicking on the appropriate button : 

![image](https://user-images.githubusercontent.com/23735987/207649789-683c4311-8a83-4336-877b-d2e8be507aad.png)

Thanks for your support !

**Comment by fallen** [comment]
For now I mark this one as closed. Please reopen it if something is missing.
