### ISSUE TITLE
[Admin] Enable user creation

### ISSUE THREAD

**Issue by fsellaouti** [pytition/Pytition#317]
**Context :**
We are using an instance with ALLOW_REGISTER = False.
With this configuration, users cannot register and there is no way for the administrator to create an account for users (petition creators) directly from the web app.

**Solution :** In the settings page, if the user is **superuser**, add a form for user creation.

**Comment by fallen** [comment]
@fsellaouti This is not documented but you can use Django's official admin interface to create accounts when ALLOW_REGISTER is False.

You can browse it at https://yourinstance/admin

Does this work for you? Do you still think we need another interface?

Thanks for the report!

**Comment by fsellaouti** [comment]
@fallen 
I didn't know this admin interface. It should be enough.
Thanks !
