### ISSUE TITLE
logo design

### ISSUE THREAD

**Issue by reallinfo** [pytition/Pytition#37]
Hello @fallen 

I am designing logos to support open source software. Do you want me to design a logo for you? I think this warehouse doesn't have a logo. I will wait for feedback. Have a nice day!

**Comment by fallen** [comment]
Hello @reallinfo!
That would be really nice of you!
I am really not into graphical design so I am totally up to any contribution of this kind since I won't be able to do it myself.
What kind of input would you need from me?

**Comment by reallinfo** [comment]
Hi again, sorry for late answer.  

I designed a logo inspired by the information in the read me file. how do these look? you can also tell me if there is something you want to edit.

![pyt](https://user-images.githubusercontent.com/36298335/49150881-3b58a100-f31f-11e8-8d7e-585b17a3f911.jpg)

**Comment by reallinfo** [comment]
I think I found a better idea. This logo represents the application better. ( python and Application function ) What do you think? Also, about the license: https://creativecommons.org/licenses/by/4.0/

![pytition](https://user-images.githubusercontent.com/36298335/50015739-4d516980-ffd8-11e8-951a-38365227018a.jpg)

**Comment by fallen** [comment]
Those seem very promising to me, very good idea!
I've asked the Python trademark people for authorization to use derivated work from Python logo (as stated there: https://www.python.org/community/logos/).
Waiting for their feedback on this :)

What would you think of mixing together your first idea with the new one?
Like putting the "Pythonic pen" inside a petition. Something like "this": 
![ae3942e4-2b97-4b41-8097-1a0def79fd24](https://user-images.githubusercontent.com/151032/50056318-cf699b80-015a-11e9-9914-601f29596b7c.png)

(thx @SylvainDe for the quick drawing!)

**Comment by reallinfo** [comment]
How is this? :)

![pyt](https://user-images.githubusercontent.com/36298335/50059145-28095a80-0194-11e9-97e7-de1d399a49d4.jpg)

**Comment by SylvainDe** [comment]
I love it, even better than my contribution above ;-)
The PSF might see it differently though.

**Comment by fallen** [comment]
I like this very much also! I hope it will be OK with PSF, let me ask them.
Thanks again!

**Comment by reallinfo** [comment]
You're welcome. I'll wait for feedback from you. Have a nice day!

**Comment by DavidMertz** [comment]
David Mertz...
Co-chair Python Software Foundation Trademarks Committee

This version in https://github.com/fallen/Pytition/issues/37#issuecomment-447678287 is clearly derivative and alters the shape. It is not a permissible use.

Please look at https://www.python.org/psf/trademarks/. 

Specifically,

> As a guideline, modifications that leave the shape -- but not necessarily the colors -- unaltered are likely to be approved. Inclusion of other visual elements at an offset to the logo is generally acceptable (subject to other terms of this policy). Modifications that modify or obscure any part of the shape of the logo will not be approved.

Numerous designs have followed this by keeping the logo intact but placing it nearby other new elements. This restriction is a matter of law, not simply if preference. Allowing derived modifications such as yours created what is called *dilution* that can reduce or eliminate our legal right to protect the mark at all.

There are other logos that we can consider "inspired by but not derived from" the Python logo. These do not directly use visual elements of the protected "two snakes" but in some way suggest it. The best example I know of is the PyCon China design.

PyCon Israel is derived but not dilutive.

Pycon Thailand would be unacceptable. We were not aware of it; however Thailand is not subject to a current registration jurisdiction, so technically we have no enforcement power.

![pyconisrael](https://user-images.githubusercontent.com/2380665/50601566-8a47a800-0e82-11e9-9e5f-3dfe072e7dff.png)
![pyconthailand](https://user-images.githubusercontent.com/2380665/50601572-8f0c5c00-0e82-11e9-9f5d-fdb525dc30c7.png)
![pyconchina](https://user-images.githubusercontent.com/2380665/50601553-81ef6d00-0e82-11e9-8756-aace59d30b25.png)

**Comment by fallen** [comment]
Hello @DavidMertz thank you for your answer here.
Here are some new proposals for approval by PSF as logo for the Pytition project.
I took inspiration from the two dragons which are not snakes but are a reference to the two snakes.
I tried to do the same with pens, which are not snakes but a reference to the two snakes.
Here is the draft: 

![logo_a](https://user-images.githubusercontent.com/151032/52538434-e56a9580-2d72-11e9-86a7-6403bb366d28.png)
![logo_b](https://user-images.githubusercontent.com/151032/52538436-e7ccef80-2d72-11e9-8a46-4f07d101c460.png)
![logo_c](https://user-images.githubusercontent.com/151032/52538438-e996b300-2d72-11e9-9c50-22cd6299a491.png)
![logo_c_bis](https://user-images.githubusercontent.com/151032/52538439-eac7e000-2d72-11e9-8274-0c0ee3f3cdb3.png)

PS: A is just the Python logo, but inside a petition clipboard

**Comment by DavidMertz** [comment]
@fallen I'm awaiting the input of other members of the PSF TC.  But my own inclination is that design A is still probably dilutive, simply because it is *too* recognizable (even if no literal shape element is quite copied).  The later ones, but especially C and D are clearly something different that only bear indirect inspiration from the Python logo.  In that way, I do not think they will be dilutive.

**Comment by fallen** [comment]
@DavidMertz Hello, thank for your quick argumented reply. Any news from other PSF TC members? Thanks :)

**Comment by DavidMertz** [comment]
I'll nudge them, but I think going by my advice will be the committee sentiment.

**Comment by spiderweak** [comment]
@DavidMertz I've discussed a bit with @fallen about the logo he provided above

Below is a vectorized version of logo C_bis (provided here in png, I will provide the svg once I have the right computer on hand)

I tried to stick as close to the drawing as possible.

@fallen asked if I could provide one with Python's color (as shown below) but we would need the PSF TC input on whereas we can use them or not.

![blacknwhite](https://user-images.githubusercontent.com/10402013/53012188-968fc080-3442-11e9-9e2e-17aebd2f1e27.png)

![color](https://user-images.githubusercontent.com/10402013/53012190-98f21a80-3442-11e9-83d2-b47eba10ed44.png)

**Comment by DavidMertz** [comment]
Just to follow up a little more.  Since you are aiming at "inspired by but not derived from" the latest versions skirt the edge too closely.  The hand drawings in https://github.com/pytition/Pytition/issues/37#issuecomment-462164129 have squared off corners that create more visual distance from the trademark protected PSF "two snakes" logo.

The probably computer rendered ones at https://github.com/pytition/Pytition/issues/37#issuecomment-465096859 add back in curved corners that are almost identical to those in the actual Python logo.  Restoring a bit more visual distinction with the more squared corners would satisfy our concerns.

**Comment by spiderweak** [comment]
@DavidMertz 
Thanks for the answer,

By squared off corners, do you mean stuf like below : 

![final_v2_bis_color](https://user-images.githubusercontent.com/10402013/54938989-c3466480-4f27-11e9-9d79-89aa96ba12f8.png)
![final_v2_ter_color](https://user-images.githubusercontent.com/10402013/54938992-c3466480-4f27-11e9-94e5-c64c74efb946.png)

**Comment by DavidMertz** [comment]
Yes. Those address the issue of too-similar corner shapes while still having the two-snakes inspiration.

**Comment by fallen** [comment]
@spiderweak hey! I hope you're well!
Thanks for the new proposal :)
Would you have a bit of time for some modifications ?

I would go for the first one but with the following modifications:

* About the lines separating the 2 snakes/pen. I would make the two vertical lines a bit wavy like the horizontal one.
* Also, I would put some bold on all the black lines. By discussing it with the person who did the hand-drawing, the lines happear too thin compared to the clipboard's bold lines.

Thanks :)

**Comment by spiderweak** [comment]
Yup, I can do that,
I don't have time for now but I should have enough time to do the modifications you ask by the end of the week.

**Comment by fallen** [comment]
> Yup, I can do that,
> I don't have time for now but I should have enough time to do the modifications you ask by the end of the week.

Thanks a lot!

**Comment by spiderweak** [comment]
![logo_v2_pytition](https://user-images.githubusercontent.com/10402013/71253714-f25bfc00-2328-11ea-8b79-16c68ca99b51.png)
Here it is.
I changed the colors a bit too, don't hesitate if you need other modifications

**Comment by fallen** [comment]
I'm closing this. No more progress in this issue for years.
