### ISSUE TITLE
Refresh up French and English translations

### ISSUE THREAD

**Issue by fallen** [pytition/Pytition#53]
It's been a long time since I last rebuilt the French and English translation files.
They surely need some love :)

**Comment by SylvainDe** [comment]
Which part do you need help for ? English or French ?

**Comment by fallen** [comment]
I've just updated the French locale file with `manage.py makemessages -a` + `git commit -am` + `git push`
It is now ready to accept translation contributions :)
See https://github.com/fallen/Pytition/commit/98b4d373ff9de4860225c1ed38f014bb892ebd48 and https://github.com/fallen/Pytition/pull/71

**Comment by fallen** [comment]
Fixed by https://github.com/pytition/Pytition/pull/124 and https://github.com/pytition/Pytition/pull/147
