### ISSUE TITLE
Image and title clickable

### ISSUE THREAD

**Issue by spiderweak** [pytition/Pytition#67]
I don't know if it is wanted but the only way to access a petition from the /petition/ page is to click on the sign button.
I think making the petition title and its image clickable would be a good enhancement. A first time user would most likely click on the title to access the petition content instead of signing the petition having only read a short text about it (the sign button gives the intuition that the link means to sign right on the spot instead of accessing the whole content)

**Comment by fallen** [comment]
Good point!
Today the "Sign !" button is in fact just a "go to the petition page" button.
I guess this button should therefore be renamed as "Display" or "View" or something like that.

But I like the idea of the image and title being clickable! Good idea!

**Comment by Te-k** [comment]
This is fixed with the last UI improvements, we can close

**Comment by fallen** [comment]
Awesome :)
Closing!
