### ISSUE TITLE
Design and implement an Organization page

### ISSUE THREAD

**Issue by Te-k** [pytition/Pytition#97]
**Is your feature request related to a problem? Please describe.**

When a user sign a petition, they may want to know who is promoting it, so we need to have a public page for an organization describing it.

**Describe the solution you'd like**

A simple webpage with the organization name and description with a list of petitions.

An example of what it could look like :

![image](https://user-images.githubusercontent.com/15989628/56125735-e0e07a00-5f79-11e9-8aa2-8b33d57e2021.png)

**Comment by fallen** [comment]
There is a public page for an organization, listing petitions: http://localhost:8000/petition/org/org-slug-name

It is accessible by clicking on the name of the org on the left of your own dashboard if you are part of the organization.

Petitions url also give a hint about the Organization who's created it: http://localhost:8000/petition/org/org-slug-name/petition-slug-title

But I think this URL is for now only used in the org dashboard and not on the org profile, that would need a fix.

Also I'm not sure petition slug name are completely implemented as this is part of #91 

But maybe some other graphical hints would be nice to add to the petition template to show the Organization name

**Comment by fallen** [comment]
I think this is done, right?

**Comment by Te-k** [comment]
Yes, what's left is in #135 (adding logo, description, website etc.)
